[build]
builder = "nixpacks"

[deploy]
startCommand = 'echo "DB=$DATABASE_URL" && flask db upgrade && flask seed && gunicorn wsgi:application --bind 0.0.0.0:$PORT --workers 2'

[deploy.envs]
DATABASE_URL = "postgresql://your-actual-connection-string-here"
